apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
          - name: VAULT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: vault-client-secret
                key: VAULT_CLIENT_SECRET