server:
  # ha:
  #   enabled: true
  #   replicas: 3
  # dataStorage:
  #   enabled: true
  #   size: 10Gi
  #   storageClass: ''
  # auditStorage:
  #   enabled: true
  #   size: 10Gi
  #   storageClass: ''
  standalone:
    enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

ui:
  enabled: true
  serviceType: ClusterIP

injector:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

global:
  openshift: false
