apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-letsencrypt-pvc
  namespace: nginxproxymanager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-letsencrypt-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
  namespace: nginxproxymanager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-data-pv
  storageClassName: ""

