title: "My Homelab"
subtitle: "Cowlab"
logo: "assets/icons/smallcow.png"
header: true
footer: false

theme: default
colors:
  light:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

  dark:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

stylesheet:
  - "assets/custom.css"

services:
  - name: "Media"
    icon: "fas fa-photo-film"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.jpg"
        keywords: "Jellyfin"
        url: "https://jellyfin.cowlab.org/"
        target: "_blank"
      - name: "Jellyseerr"
        logo: "assets/icons/jellyseerr.jpg"
        keywords: "Jellyseerr"
        url: "https://jellyseerr.cowlab.org"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/icons/sonarr.jpg"
        keywords: "Sonarr"
        url: "https://sonarr.cowlab.org/"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/icons/radarr.jpg"
        keywords: "Radarr"
        url: "https://radarr.cowlab.org/"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/icons/readarr.jpg"
        keywords: "Readarr"
        url: "https://readarr.cowlab.org/"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/icons/lidarr.jpg"
        keywords: "Lidarr"
        url: "https://lidarr.cowlab.org/"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.jpg"
        keywords: "Prowlarr"
        url: "https://prowlarr.cowlab.org/"
        target: "_blank"

  - name: "Services"
    icon: "fas fa-bars-staggered"
    items:
      - name: "Nextcloud"
        logo: "assets/icons/nextcloud.jpg"
        keywords: "Nextcloud"
        url: "https://nextcloud.cowlab.org/"
        target: "_blank"
      - name: "Valutwarden"
        logo: "assets/icons/vaultwarden.jpg"
        keywords: "Vaultwarden"
        url: "https://vaultwarden.cowlab.org/"
        target: "_blank"
      - name: "Qbittorrent"
        logo: "assets/icons/qbittorrent.jpg"
        keywords: "Qbittorrent"
        url: "https://qbittorrent.cowlab.org/"
        target: "_blank"

  - name: "System"
    icon: "fas fa-gear"
    items:
      - name: "PiHole"
        logo: "assets/icons/pi-hole.jpg"
        keywords: "PiHole"
        url: "https://pihole.cowlab.org"
        target: "_blank"
      - name: "Pikvm"
        logo: "assets/icons/pikvm.jpg"
        keywords: "Pikvm"
        url: "https://pikvm.cowlab.org/"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/icons/grafana.jpg"
        keywords: "Grafana"
        url: "https://grafana.cowlab.org/"
        target: "_blank"
      - name: "Argocd"
        logo: "assets/icons/argocd.jpg"
        keywords: "Argocd"
        url: "https://argocd.cowlab.org/"
        target: "_blank"
      - name: "Traefik"
        logo: "assets/icons/traefik.jpg"
        keywords: "Traefik"
        url: "https://traefik.cowlab.org/"
        target: "_blank"
      - name: "Vault"
        logo: "assets/icons/vault.jpg"
        keywords: "Vault"
        url: "https://vault.cowlab.org/"
        target: "_blank"
      - name: "Longhorn"
        logo: "assets/icons/longhorn.jpg"
        keywords: "Longhorn"
        url: "https://longhorn.cowlab.org/"
        target: "_blank"
