apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: homer-config
    namespace: homer
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    behavior: create
    files:
     - config.yml=config.yaml

  - name: homer-icons
    namespace: homer
    options:
      disableNameSuffixHash: true
    files:
      - argocd.jpg=icons/argocd.jpg
      - grafana.jpg=icons/grafana.jpg
      - jellyfin.jpg=icons/jellyfin.jpg
      - jellyseerr.jpg=icons/jellyseerr.jpg
      - kubernetes.jpg=icons/kubernetes.jpg
      - lidarr.jpg=icons/lidarr.jpg
      - nextcloud.jpg=icons/nextcloud.jpg
      - pi-hole.jpg=icons/pi-hole.jpg
      - pikvm.jpg=icons/pikvm.jpg
      - prowlarr.jpg=icons/prowlarr.jpg
      - qbittorrent.jpg=icons/qbittorrent.jpg
      - radarr.jpg=icons/radarr.jpg
      - readarr.jpg=icons/readarr.jpg
      - sonarr.jpg=icons/sonarr.jpg
      - traefik.jpg=icons/traefik.jpg
      - vault.jpg=icons/vault.jpg
      - vaultwarden.jpg=icons/vaultwarden.jpg
      - favicon.ico=icons/favicon.ico
      - smallcow.jpg=icons/smallcow.jpg