apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - icons-pvc.yaml

configMapGenerator:
  - name: homer-config
    namespace: homer
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    behavior: create
    files:
     - config.yml=config.yaml
