# AWS Credentials for Palworld Automation
# This file was auto-generated by Terraform
# Append this to your ~/.aws/credentials file or use it standalone

[${profile_name}]
aws_access_key_id = ${access_key_id}
aws_secret_access_key = ${secret_access_key}
region = ${region}
