apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pihole-redirect
  namespace: pihole
spec:
  redirectRegex:
    regex: "^/(|index.html)$"
    replacement: "/admin/"
    permanent: true
