apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: jellyseerr
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.cowlab.org`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
  tls:
    secretName: cowlab-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-cert
  namespace: jellyseerr
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"
