apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloudflare-token: '{{ .CLOUDFLARE_API_TOKEN | replace "\n" "" | replace "\r" "" }}'
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: ff56d6cb-87a4-4a1c-bc68-cb04153c177f
