apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- discord-bot
- homer
- jellyseerr
- monitoring
# - nextcloud
- vaultwarden
- jellyfin
- sonarr
- radarr
- readarr
- lidarr
- prowlarr
- longhorn
# - nginxproxymanager
# - qbittorrent
# - wireguard
# - vault
# - external-secrets
