apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{APP_NAME}}-data
  namespace: {{APP_NAME}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{STORAGE_SIZE}}
  volumeName: {{APP_NAME}}-data
  storageClassName: ""
