apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{APP_NAME}}-data
spec:
  capacity:
    storage: {{STORAGE_SIZE}}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/data
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain
