apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: prowlarr
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.cowlab.org`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: cowlab-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-cert
  namespace: prowlarr
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"
