apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-homer-assets
    volumeAttributes:
      source: "//10.0.0.150/media"
    nodeStageSecretRef:
      name: smb-secret
      namespace: kube-system
