apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-cert
  namespace: homer
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"