title: "My Homelab"
subtitle: "Cowlab"
logo: "assets/icons/smallcow.png"
header: true
footer: false

# message:
#  content: '<iframe src="" style="overflow:hidden;margin:0;padding:0;width:calc(100% - 100px);height:60px;" frameborder="0"></iframe>'

theme: default
colors:
  light:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

  dark:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

stylesheet:
  - "assets/custom.css"

links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute

services:
  - name: "Media"
    icon: "fas fa-photo-film"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        keywords: "Jellyfin"
        url: "https://jellyfin.cowlab.org/"
        target: "_blank"
      - name: "Jellyseerr"
        logo: "assets/tools/jellyseerr.png"
        keywords: "Jellyseerr"
        url: "https://jellyseerr.cowlab.org"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        keywords: "Sonarr"
        url: "https://sonarr.cowlab.org/"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        keywords: "Radarr"
        url: "https://radarr.cowlab.org/"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/tools/readarr.png"
        keywords: "Readarr"
        url: "https://readarr.cowlab.org/"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.png"
        keywords: "Lidarr"
        url: "https://lidarr.cowlab.org/"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        keywords: "Prowlarr"
        url: "https://prowlarr.cowlab.org/"
        target: "_blank"

  - name: "Services"
    icon: "fas fa-bars-staggered"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        keywords: "Nextcloud"
        url: "https://nextcloud.cowlab.org/"
        target: "_blank"
      - name: "Valutwarden"
        logo: "assets/tools/vaultwarden.png"
        keywords: "Vaultwarden"
        url: "https://vaultwarden.cowlab.org/"
        target: "_blank"
      - name: "Qbittorrent"
        logo: "assets/tools/qbittorrent.png"
        keywords: "Qbittorrent"
        url: "https://qbittorrent.bigbees.duckdns.org/"
        target: "_blank"

  - name: "System"
    icon: "fas fa-gear"
    items:
      - name: "PiHole"
        logo: "assets/tools/pi-hole.png"
        keywords: "PiHole"
        url: "https://pihole.bigbees.duckdns.org/admin"
        target: "_blank"
      - name: "Pikvm"
        logo: "assets/tools/pikvm.png"
        keywords: "Pikvm"
        url: "https://pikvm.bigbees.duckdns.org/"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        keywords: "Grafana"
        url: "https://grafana.cowlab.org/"
        target: "_blank"
      - name: "Argocd"
        logo: "assets/tools/argocd.png"
        keywords: "Argocd"
        url: "https://argocd.cowlab.org/"
        target: "_blank"
      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        keywords: "Traefik"
        url: "https://traefik.cowlab.org/"
        target: "_blank"
      - name: "NginxProxyManager"
        logo: "assets/tools/nginx-proxy-manager.png"
        keywords: "Nginxproxymanager"
        url: "https://nginxproxymanager.cowlab.org/"
        target: "_blank"
