apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: assets-volume
          mountPath: /www/assets
          subPath: homer/assets
        - name: homer-config
          mountPath: /www/assets/config.yml
          subPath: config.yml
      volumes:
      - name: assets-volume
        persistentVolumeClaim:
          claimName: homer-assets-pvc
      - name: homer-config
        configMap:
          name: homer-config 