apiVersion: v1
kind: Pod
metadata:
  name: homer-init
  namespace: homer
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: icons-volume
          mountPath: /mnt/icons
  volumes:
    - name: icons-volume
      persistentVolumeClaim:
        claimName: homer-icons-pvc
