apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-icons-pvc
  namespace: homer
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
