apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-assets-pvc
  namespace: homer
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi #5Mb
