apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: sonarr
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.cowlab.org`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls:
    secretName: cowlab-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-cert
  namespace: sonarr
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"
