---
- name: Label pi-agent1
  ansible.builtin.command: >
    kubectl label node pi-agent1 node-type=raspberry-pi --overwrite
  register: label_agent1
  changed_when: "'already has' not in label_agent1.stderr"

- name: Label pi-agent2
  ansible.builtin.command: >
    kubectl label node pi-agent2 node-type=raspberry-pi --overwrite
  register: label_agent2
  changed_when: "'already has' not in label_agent2.stderr"

- name: Label pi-server
  ansible.builtin.command: >
    kubectl label node pi-server node-type=raspberry-pi --overwrite
  register: label_server
  changed_when: "'already has' not in label_server.stderr"

- name: Label homelab
  ansible.builtin.command: >
    kubectl label node homelab node-type=ubuntu --overwrite
  register: label_homelab
  changed_when: "'already has' not in label_homelab.stderr"
