apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID | replace "\n" "" | replace "\r" "" }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY | replace "\n" "" | replace "\r" "" }}'
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: b52d37bc-b59d-4e2d-8a42-4be20f503b75
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 53bafbba-8103-4e5a-9713-7720f9e18cc8
      property: AWS_SECRET_ACCESS_KEY
