repositories:
  - name: k8sgpt
    url: https://charts.k8sgpt.ai/

releases:
  - name: k8sgpt-operator
    namespace: k8sgpt-operator-system
    createNamespace: true
    chart: k8sgpt/k8sgpt-operator
    version: v0.2.0
    values:
      - rbac:
          create: true
        serviceAccount:
          create: true
          name: k8sgpt-operator-controller-manager