apiVersion: v1
kind: Secret
metadata:
  name: k8sgpt-secret
  namespace: k8sgpt-operator-system
type: Opaque
stringData:
  openai-api-key: c2stcHJvai1Wa2FadVQ1UE9sdmlLZElCNExHdFQzQmxia0ZKSkdsdFQzVDRueGJtdkxTS0tGR0Y=
