apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  namespace: lidarr
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.cowlab.org`)
      kind: Rule
      services:
        - name: lidarr
          port: 8686
  tls:
    secretName: cowlab-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-cert
  namespace: lidarr
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"
