apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
