apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-pvc
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: readarr-config-pv
  storageClassName: ""
