apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filegator-pvc
  namespace: filegator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: filegator-pv
  storageClassName: ""