---
- name: Add jetstack Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Update Helm jetstack repositories
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    force_update: yes

- name: Create cert-manager namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: cert-manager
    state: present

- name: Apply cert-manager CRDs
  kubernetes.core.k8s:
    state: present
    src: https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.crds.yaml

- name: Install cert-manager Helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    values: "{{ lookup('file', '../vars/values.yaml') | from_yaml }}"
    chart_version: 1.15.3
    state: present

- name: Apply issuers secrets
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret-cf-token.j2') }}"
  
# - name: Apply Staging ClusterIssuer
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'letsencrypt-staging.j2') }}"

# - name: Apply Stagging Certificate
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'staging-cert.j2') }}"

- name: Apply Production ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-production.j2') }}"

- name: Apply Production Certificate
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'prod-cert.j2') }}"
