---
- name: Add Traefik Helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Update Helm repositories
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik
    force_update: yes

- name: Create Traefik namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: traefik
    state: present

- name: Get all namespaces
  kubernetes.core.k8s_info:
    kind: Namespace
  register: namespaces

- name: Install Traefik Helm chart
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    values: "{{ lookup('file', '../vars/values.yaml') | from_yaml }}"
    state: present

- name: Get all services
  kubernetes.core.k8s_info:
    kind: Service
    namespace: traefik
  register: services

- name: Get Traefik pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: traefik
  register: pods

- name: Generate base64-encoded admin password
  shell: htpasswd -nb admin password | openssl base64
  register: base64_password

- debug:
    var: base64_password.stdout

- name: Apply Traefik dashboard secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret-dashboard.j2') }}"

- name: Get secrets in Traefik namespace
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: traefik
  register: secrets

- name: Apply Traefik ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.j2') }}"
