apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-data
  namespace: readarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: readarr-data
  storageClassName: ""