apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-reader
  namespace: external-secrets
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-reader-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: vault-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-reader-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-reader-rolebinding
subjects:
  - kind: ServiceAccount
    name: vault-reader
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: vault-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"  # Base path in Vault
      version: "v2"   # Vault API version
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: vault-reader
