kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: vaultwarden
  name: external-secret-vaultwarden
spec:
  podSelector:
    matchLabels:
      app: vaultwarden
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: external-secrets
            app.kubernetes.io/name: external-secrets