apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: docker-config/radarr/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: radarr-config-pvc
